Code Review
edubew/code_review pull request #1
Opened 2022-04-25 08:45 UTC by edubew

# Code review practice
- Perform a code review on a past project from microverse trials

2022-04-25 09:00 UTC, edubew reviewed
# Highlights
- Good job
- The workflow is good
- Add linters to your project

2022-04-25 09:37 UTC, sja-thedude commented
> # Highlights
> * Good job
> * The workflow is good
> * Add linters to your project

- [ ] Kindly make sure to add a Required changes section after Highlights and write a comment like "Kindly make sure to add all the linters correctly by copying them from [here](https://github.com/microverseinc/linters-config/tree/master/html-css)"

2022-04-25 09:50 UTC, sja-thedude requested changes
## Required Changes ♻️

Hi @edubew, This is @sja-thedude your code reviewer.

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![768070f3-bc9a-4aba-b8bc-25793e00ea1e_text](https://user-images.githubusercontent.com/70269507/159483175-2f61461d-b352-4cb4-98f8-b173e05ab5ff.gif)

## Highlights
✔️ Good job so far in trying to review your code.

## Required 
- [x] Kindly check the quoted reply to rephrase your comment [here](https://github.com/edubew/code_review/pull/1#issuecomment-1108329943).
- [x] Kindly add Github inline comments at least once to leave review comments. Make sure to leave the comment under a line or block of code that fits the context the comment is about.
_I have attached a video which shows how you can add an inline comment._

https://user-images.githubusercontent.com/70269507/165065141-85b8ce37-ff27-4c19-ba41-ac6d6b28fd3d.mov

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@sja-thedude] in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-30 07:55 UTC, edubew reviewed
# Required
Kindly check the comments below and make changes

2022-04-30 07:55 UTC, edubew commented on style.css
> +  }
Kindly remove the extra space to make the code cleaner.

2022-04-30 07:55 UTC, edubew commented on style.css
> +    }
Kindly include this part of the code inside the media query to make to make the elements responsive to different screen sizes

2022-04-30 07:55 UTC, edubew commented on index.html
> +            </div>
Kindly remove the extra space here for a cleaner code

2022-04-30 08:43 UTC, gtekle approved these changes
Hi @edubew :wave: , 

# STATUS: APPROVED 🎉🎉🎉

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
:heavy_check_mark: Used polite suggestions
:heavy_check_mark: Added inline comments

## Optional suggestions
- [ Optional ] You should use appropriate options at the bottom when you do the review. If you requested required changes, you should as well select the Request changes option as in the screenshot below.
![review-past-proj](https://user-images.githubusercontent.com/44057863/166098617-5f38eaac-77f4-47da-b77d-25c52950b09a.png)


_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-30 09:20 UTC, edubew commented
Hello @gtekle, Thank you for the review.
In your optional comments, you suggested that I should use the appropriate options button, for instance, "request changes" for this exercise but since I m the author of the pull request that I am reviewing, that option is blocked for me and I can only use the comments option

2022-04-30 09:26 UTC, merged

2022-04-30 09:47 UTC, gtekle commented
Thanks, @edubew :+1: 
Noted!